### PR TITLE
Gridworld simpler

### PR DESCRIPTION
**Pull request by jjfiv**
I reorganized the code to support safety gridwolrd and patrol gridworld. This drastically breaks backwards compatibility.

### CODE REVIEW

**Comment by etosch** [comment]
Are you supposed to be teaching?

Emma Tosch
PhD Candidate, Knowledge Discovery Laboratory
College of Information and Computer Sciences 
University of Massachusetts Amherst
etosch@cs.umass.edu

**Comment by jjfiv** [comment]
I used this as an example of making a pull request from a branch. Not urgent.

**Comment by etosch** [comment]
Clever, Professor!

Emma Tosch
PhD Candidate, Knowledge Discovery Laboratory
College of Information and Computer Sciences 
University of Massachusetts Amherst
etosch@cs.umass.edu

**Comment by etosch** [comment]
Do we still want to merge this PR?

**Comment by jjfiv** [comment]
Leaving it open for now but needs to move to the other repo.

**Pull request closed without merging**
