### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by kclary**
After a quick glance over, I'd like someone to check
- [x] changes to sklearn - I kept it in the requirements but moved the import to the only function where it's used
- [x] I added back some of the gym/turtle utils that were bombed out when we removed baselines

### CODE REVIEW

**Review by jjfiv — APPROVED** [review]
I'm happy to have these changes in.
Maybe it's time to revisit the naming of "get_turtle"... we could leave it, but also have:

```python
def get_innermost_env(env: gym.Env) -> gym.Env:
  return get_turtle(env)
```

**Comment by kclary** [comment]
I like that addition/rename for `get_turtle`. `_reset_deep_kludge` could also do with a name change as well...though I don't think that was actually used in any of my recent stuff, so maybe we just yank that out again. I don't recall the specifics for what that function was handling anyway

**Review by etosch — APPROVED** [review]
LGTM!

**Comment by etosch** [comment]
@jjfiv gave me a hard time about merging this before the discussion of turtles, but honestly that should go into a separate pull request. We can discuss and merge on Friday.

**Pull request merged**
